/**
 * Market observation schema.
 *
 * Every observation carries TWO timestamps:
 *   marketTime  the venue / exchange / block timestamp of the event (when it happened)
 *   obsTime     the local receive time: when a strategy running against this feed could
 *               first have seen it. Decisions are gated on obsTime, never on marketTime.
 *
 * Replay order is by (obsTime, seq). `seq` is the explicit position in the fixture stream
 * and must be strictly increasing; obsTime must be non-decreasing with seq.
 */
import {
  type Decimal,
  PRICE_SCALE,
  QTY_SCALE,
  fmtPrice,
  fmtQty,
  parsePrice,
  parseQty,
} from '../core/money.js';
import { canonicalJson, sha256Hex } from '../core/hash.js';

export const FIXTURE_SCHEMA_VERSION = 1 as const;

/** The label every synthetic fixture header MUST carry verbatim. */
export const SYNTHETIC_LABEL =
  'SYNTHETIC DATA: generated by a seeded simulator. Not real market data. Results derived from it are research output only and imply nothing about live profitability.';

export type Aggressor = 'buy' | 'sell' | 'unknown';

export interface Level {
  price: bigint;
  size: bigint;
}

export interface MarketEventBase {
  eventId: string;
  /** Explicit stream position; strictly increasing. */
  seq: number;
  /** Local receive time (ms epoch). */
  obsTime: number;
  /** Venue / block timestamp (ms epoch). */
  marketTime: number;
  /** Optional block number for on-chain venues. */
  blockNumber?: number;
  symbol: string;
  venue: string;
}

export interface BookEvent extends MarketEventBase {
  type: 'book';
  /** Best first (descending price). */
  bids: Level[];
  /** Best first (ascending price). */
  asks: Level[];
}

export interface TradeEvent extends MarketEventBase {
  type: 'trade';
  tradeId: string;
  price: bigint;
  size: bigint;
  aggressor: Aggressor;
}

export type MarketEvent = BookEvent | TradeEvent;

export interface FixtureProvenance {
  source: 'synthetic' | 'recorded';
  description: string;
  generator?: string;
  generatorVersion?: string;
  seed?: number;
  /** For recorded data: where it came from and how obsTime was captured. */
  recordedFrom?: string;
  captureMethod?: string;
  timeBasis: {
    obsTime: string;
    marketTime: string;
  };
}

export interface FixtureHeader {
  type: 'header';
  schemaVersion: typeof FIXTURE_SCHEMA_VERSION;
  symbol: string;
  venue: string;
  priceScale: number;
  qtyScale: number;
  tickSize: Decimal;
  lotSize: Decimal;
  /** Replay clock origin (ms epoch). Windows and ticks are aligned to this. */
  startTime: number;
  /** Nominal end of the fixture (ms epoch). */
  endTime: number;
  eventCount: number;
  synthetic: boolean;
  /** Required and must equal SYNTHETIC_LABEL when synthetic === true. */
  syntheticLabel?: string;
  provenance: FixtureProvenance;
}

export interface Fixture {
  header: FixtureHeader;
  events: MarketEvent[];
}

// ---------------------------------------------------------------------------
// Wire format (JSONL): header line followed by one event per line. Prices and
// quantities are decimal strings so the file is unambiguous and tool-friendly.
// ---------------------------------------------------------------------------

export interface WireLevel {
  price: Decimal;
  size: Decimal;
}

interface WireBase {
  eventId: string;
  seq: number;
  obsTime: number;
  marketTime: number;
  blockNumber?: number;
  symbol: string;
  venue: string;
}

export interface WireBookEvent extends WireBase {
  type: 'book';
  bids: WireLevel[];
  asks: WireLevel[];
}

export interface WireTradeEvent extends WireBase {
  type: 'trade';
  tradeId: string;
  price: Decimal;
  size: Decimal;
  aggressor: Aggressor;
}

export type WireMarketEvent = WireBookEvent | WireTradeEvent;

export function toWire(ev: MarketEvent): WireMarketEvent {
  const base: WireBase = {
    eventId: ev.eventId,
    seq: ev.seq,
    obsTime: ev.obsTime,
    marketTime: ev.marketTime,
    symbol: ev.symbol,
    venue: ev.venue,
  };
  if (ev.blockNumber !== undefined) base.blockNumber = ev.blockNumber;
  if (ev.type === 'book') {
    return {
      ...base,
      type: 'book',
      bids: ev.bids.map((l) => ({ price: fmtPrice(l.price), size: fmtQty(l.size) })),
      asks: ev.asks.map((l) => ({ price: fmtPrice(l.price), size: fmtQty(l.size) })),
    };
  }
  return {
    ...base,
    type: 'trade',
    tradeId: ev.tradeId,
    price: fmtPrice(ev.price),
    size: fmtQty(ev.size),
    aggressor: ev.aggressor,
  };
}

export function fromWire(w: WireMarketEvent): MarketEvent {
  const base: MarketEventBase = {
    eventId: String(w.eventId),
    seq: Number(w.seq),
    obsTime: Number(w.obsTime),
    marketTime: Number(w.marketTime),
    symbol: String(w.symbol),
    venue: String(w.venue),
  };
  if (w.blockNumber !== undefined) base.blockNumber = Number(w.blockNumber);
  if (w.type === 'book') {
    return {
      ...base,
      type: 'book',
      bids: w.bids.map((l) => ({ price: parsePrice(l.price), size: parseQty(l.size) })),
      asks: w.asks.map((l) => ({ price: parsePrice(l.price), size: parseQty(l.size) })),
    };
  }
  if (w.type === 'trade') {
    return {
      ...base,
      type: 'trade',
      tradeId: String(w.tradeId),
      price: parsePrice(w.price),
      size: parseQty(w.size),
      aggressor: w.aggressor,
    };
  }
  throw new Error(`unknown market event type: ${JSON.stringify((w as { type?: unknown }).type)}`);
}

export function validateHeader(h: unknown): FixtureHeader {
  if (!h || typeof h !== 'object') throw new Error('fixture header missing');
  const header = h as Partial<FixtureHeader>;
  if (header.type !== 'header') throw new Error('first fixture line must be the header');
  if (header.schemaVersion !== FIXTURE_SCHEMA_VERSION) {
    throw new Error(`unsupported fixture schema version ${String(header.schemaVersion)}`);
  }
  if (typeof header.symbol !== 'string' || typeof header.venue !== 'string') {
    throw new Error('fixture header needs symbol and venue');
  }
  if (Number(header.priceScale) !== Number(PRICE_SCALE) || Number(header.qtyScale) !== Number(QTY_SCALE)) {
    throw new Error('fixture scales do not match engine scales');
  }
  if (typeof header.synthetic !== 'boolean') throw new Error('fixture header must declare synthetic: boolean');
  if (header.synthetic) {
    if (header.syntheticLabel !== SYNTHETIC_LABEL) {
      throw new Error('synthetic fixtures must carry the exact SYNTHETIC_LABEL in syntheticLabel');
    }
    if (header.provenance?.source !== 'synthetic') throw new Error('synthetic fixture provenance.source must be "synthetic"');
  } else if (header.provenance?.source !== 'recorded') {
    throw new Error('non-synthetic fixture provenance.source must be "recorded"');
  }
  if (!Number.isInteger(header.startTime) || !Number.isInteger(header.endTime) || header.endTime! <= header.startTime!) {
    throw new Error('fixture header needs integer startTime < endTime');
  }
  if (typeof header.tickSize !== 'string' || typeof header.lotSize !== 'string') {
    throw new Error('fixture header needs tickSize and lotSize decimal strings');
  }
  return header as FixtureHeader;
}

export function serializeFixture(fixture: Fixture): string {
  const lines: string[] = [JSON.stringify(fixture.header)];
  for (const ev of fixture.events) lines.push(JSON.stringify(toWire(ev)));
  return lines.join('\n') + '\n';
}

export function parseFixture(text: string): Fixture {
  const lines = text.split('\n').filter((l) => l.trim().length > 0);
  if (lines.length === 0) throw new Error('empty fixture');
  const header = validateHeader(JSON.parse(lines[0]!));
  const events: MarketEvent[] = [];
  for (let i = 1; i < lines.length; i++) {
    events.push(fromWire(JSON.parse(lines[i]!) as WireMarketEvent));
  }
  if (header.eventCount !== events.length) {
    throw new Error(`fixture header eventCount=${header.eventCount} but ${events.length} events present`);
  }
  return { header, events };
}

/** Content hash over the canonical wire form (header + events). */
export function fixtureContentHash(fixture: Fixture): string {
  return sha256Hex(canonicalJson({ header: fixture.header, events: fixture.events.map(toWire) }));
}

export function bestBid(book: BookEvent): Level | undefined {
  return book.bids[0];
}
export function bestAsk(book: BookEvent): Level | undefined {
  return book.asks[0];
}
export function midPrice(book: BookEvent): bigint | null {
  const b = book.bids[0];
  const a = book.asks[0];
  if (!b || !a) return null;
  return (b.price + a.price) / 2n;
}
